numbers = []
num1 = int(input("Enter first number:"))
num2 = int(input("Enter second number:"))
num3 = int(input("Enter third number:"))
num4 = int(input("Enter fourth number:"))
num5 = int(input("Enter fifth number:"))
numbers.append(num1)
numbers.append(num2)
numbers.append(num3)
numbers.append(num4)
numbers.append(num5)
print("your numbers:",numbers)
print("_______________")
print("min is:",min(numbers))
print("max is:",max(numbers))